version: '3.4'

services:
  database:
    image: postgres:12.7
    environment: 
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: bluelabs
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5434:5432
  app:
    image: golang:latest
    volumes:
      - ./:/usr/src/bluelabs
    working_dir: /usr/src/bluelabs
    env_file: .env
    ports:
      - 8080:8080
    command: bash -c "cd /usr/src/bluelabs/cmd/web && go build -o ../../bin/ && ../../bin/web"
    depends_on:
      - database
